[workspace]
members = [
    "rust/library",
    "rust/test_executor",
    "problems/problems_1",
    "problems/problems_2",
	"problems/problems_2766",
    "problems/problems_279",
	"problems/problems_2844",
	"problems/problems_49",
	"problems/problems_2740",
	"problems/problems_239",
	"problems/problems_3106",
	"problems/problems_34",
	"problems/problems_102",
    "problems/problems_1379",
    "problems/problems_236",
	"problems/problems_116",
	"problems/problems_117",
	"problems/problems_133",
	"problems/problems_138",
	"problems/problems_699",
	"problems/problems_39",
	"problems/problems_215",
	"problems/problems_682",
	"problems/problems_56",
	"problems/problems_2961",
	"problems/problems_394",
	"problems/problems_3111",
	"problems/problems_5",
	"problems/problems_LCP_40",
	"problems/problems_169",
	"problems/problems_3128",
	"problems/problems_322",
	"problems/problems_3143",
	"problems/problems_21",
	"problems/problems_108",
	"problems/problems_572",
	"problems/problems_33",
	"problems/problems_98",
	"problems/problems_2808",
	"problems/problems_600",
	"problems/problems_15",
	"problems/problems_2398",
	"problems/problems_3129",
	"problems/problems_438",
	"problems/problems_3130",
	"problems/problems_48",
	"problems/problems_950",
	"problems/problems_3131",
	"problems/problems_207",
	"problems/problems_2553",
	"problems/problems_3132",
	"problems/problems_22",
	"problems/problems_2940",
	"problems/problems_55",
	"problems/problems_139",
	"problems/problems_1035",
	"problems/problems_19",
	"problems/problems_230",
	"problems/problems_2236",
	"problems/problems_762",
	"problems/problems_676",
	"problems/problems_24",
	"problems/problems_3151",
	"problems/problems_189",
	"problems/problems_1139",
	"problems/problems_3152",
	"problems/problems_199",
	"problems/problems_3148",
	"problems/problems_739",
]

[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["benhao"]
description = "LeetCode solutions in Rust"
readme = "README.md"

[[test]]
name = "solution_test"
path = "rust/test_executor/tests/test.rs"

[[test]]
name = "solutions_test"
path = "rust/test_executor/tests/solutions_test.rs"

[dependencies]
serde_json = "1.0"
rand = "0.8.4"
regex = "1.10.5"
assert_float_eq = "1"
test_executor = { path = "rust/test_executor", features = ["run_test"] }
solution_1 = { path = "problems/problems_1", features = ["solution_1"] }
solution_2 = { path = "problems/problems_2", features = ["solution_2"] }
solution_2766 = { path = "problems/problems_2766", features = ["solution_2766"] }
solution_279 = { path = "problems/problems_279", features = ["solution_279"] }
solution_2844 = { path = "problems/problems_2844", features = ["solution_2844"] }
solution_49 = { path = "problems/problems_49", features = ["solution_49"] }
solution_2740 = { path = "problems/problems_2740", features = ["solution_2740"] }
solution_239 = { path = "problems/problems_239", features = ["solution_239"] }
solution_3106 = { path = "problems/problems_3106", features = ["solution_3106"] }
solution_34 = { path = "problems/problems_34", features = ["solution_34"] }
solution_102 = { path = "problems/problems_102", features = ["solution_102"] }
solution_1379 = { path = "problems/problems_1379", features = ["solution_1379"] }
solution_236 = { path = "problems/problems_236", features = ["solution_236"] }
solution_116 = { path = "problems/problems_116", features = ["solution_116"] }
solution_117 = { path = "problems/problems_117", features = ["solution_117"] }
solution_133 = { path = "problems/problems_133", features = ["solution_133"] }
solution_138 = { path = "problems/problems_138", features = ["solution_138"] }
solution_699 = { path = "problems/problems_699", features = ["solution_699"] }
solution_39 = { path = "problems/problems_39", features = ["solution_39"] }
solution_215 = { path = "problems/problems_215", features = ["solution_215"] }
solution_682 = { path = "problems/problems_682", features = ["solution_682"] }
solution_56 = { path = "problems/problems_56", features = ["solution_56"] }
solution_2961 = { path = "problems/problems_2961", features = ["solution_2961"] }
solution_394 = { path = "problems/problems_394", features = ["solution_394"] }
solution_3111 = { path = "problems/problems_3111", features = ["solution_3111"] }
solution_5 = { path = "problems/problems_5", features = ["solution_5"] }
solution_169 = { path = "problems/problems_169", features = ["solution_169"] }
solution_3128 = { path = "problems/problems_3128", features = ["solution_3128"] }
solution_322 = { path = "problems/problems_322", features = ["solution_322"] }
solution_3143 = { path = "problems/problems_3143", features = ["solution_3143"] }
solution_21 = { path = "problems/problems_21", features = ["solution_21"] }
solution_108 = { path = "problems/problems_108", features = ["solution_108"] }
solution_572 = { path = "problems/problems_572", features = ["solution_572"] }
solution_33 = { path = "problems/problems_33", features = ["solution_33"] }
solution_98 = { path = "problems/problems_98", features = ["solution_98"] }
solution_2808 = { path = "problems/problems_2808", features = ["solution_2808"] }
solution_600 = { path = "problems/problems_600", features = ["solution_600"] }
solution_15 = { path = "problems/problems_15", features = ["solution_15"] }
solution_2398 = { path = "problems/problems_2398", features = ["solution_2398"] }
solution_3129 = { path = "problems/problems_3129", features = ["solution_3129"] }
solution_438 = { path = "problems/problems_438", features = ["solution_438"] }
solution_3130 = { path = "problems/problems_3130", features = ["solution_3130"] }
solution_48 = { path = "problems/problems_48", features = ["solution_48"] }
solution_950 = { path = "problems/problems_950", features = ["solution_950"] }
solution_3131 = { path = "problems/problems_3131", features = ["solution_3131"] }
solution_207 = { path = "problems/problems_207", features = ["solution_207"] }
solution_2553 = { path = "problems/problems_2553", features = ["solution_2553"] }
solution_3132 = { path = "problems/problems_3132", features = ["solution_3132"] }
solution_22 = { path = "problems/problems_22", features = ["solution_22"] }
solution_2940 = { path = "problems/problems_2940", features = ["solution_2940"] }
solution_55 = { path = "problems/problems_55", features = ["solution_55"] }
solution_139 = { path = "problems/problems_139", features = ["solution_139"] }
solution_1035 = { path = "problems/problems_1035", features = ["solution_1035"] }
solution_19 = { path = "problems/problems_19", features = ["solution_19"] }
solution_230 = { path = "problems/problems_230", features = ["solution_230"] }
solution_2236 = { path = "problems/problems_2236", features = ["solution_2236"] }
solution_762 = { path = "problems/problems_762", features = ["solution_762"] }
solution_676 = { path = "problems/problems_676", features = ["solution_676"] }
solution_24 = { path = "problems/problems_24", features = ["solution_24"] }
solution_3151 = { path = "problems/problems_3151", features = ["solution_3151"] }
solution_189 = { path = "problems/problems_189", features = ["solution_189"] }
solution_1139 = { path = "problems/problems_1139", features = ["solution_1139"] }
solution_3152 = { path = "problems/problems_3152", features = ["solution_3152"] }
solution_199 = { path = "problems/problems_199", features = ["solution_199"] }
solution_3148 = { path = "problems/problems_3148", features = ["solution_3148"] }
solution_739 = { path = "problems/problems_739", features = ["solution_739"] }
