[package]
name = "test_executor"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["benhao"]
description = "LeetCode Rust Test Main"
readme = "../README.md"

[features]
run_test = []

[dependencies]
serde_json = "1.0"
assert_float_eq = "1"
